name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Exécute tous les jours à minuit UTC
  workflow_dispatch:

permissions:
  contents: write  # Autorise GitHub Actions à écrire dans le dépôt

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Shidoll
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push Snake Game to Repository
        run: |
          mkdir -p output
          mv dist/* output/
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add output/
          git commit -m "Updated Snake Game contribution graph" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
