name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Exécute tous les jours à minuit UTC
  workflow_dispatch:

permissions:
  contents: write  # Permet à GitHub Actions d'écrire dans le dépôt

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Shidoll
          outputs: |
            dist/snake-dark.svg?palette=github-dark

      - name: Ensure Output Directory Exists
        run: mkdir -p output

      - name: Copy Snake Game to Output
        run: cp dist/snake-dark.svg output/snake-dark.svg
        
      - name: Push Snake Game to Repository
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add output/snake-dark.svg
          git commit -m "Updated weekly Snake Game animation" || echo "No changes to commit"
          git pull --rebase origin main  # Synchronisation pour éviter les conflits
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
